#!/usr/bin/env python3
"""
vintage-ad-generator: compose a finished period newspaper-ad layout from an
engraving "cut" (AI-generated illustration) + real period TYPE (fonts).

WHY the type is set here and NOT generated by the diffusion model: local models
garble words ("OUSTER", gibberish banners). Real ads were a printer's engraved
cut + hand-set type anyway, so setting the words as fonts is both more authentic
AND 100% legible. Run with ComfyUI's venv python (it has Pillow).

Example:
  <comfyui-python> make_tee_mock.py --cut cut.png --headline "GALLOWAY'S" \
      --services "GENERAL MERCHANDISE  ·  GAS" --town "SHALLOTTE, N. C." \
      --kicker "AROUND THE CLOCK" --tagline "GAS · OILS · LUNCHES — OPEN ALL HOURS" \
      --out finished.png
"""
import argparse
import os
from PIL import Image, ImageDraw, ImageFont, ImageOps

FDIR = "C:/Windows/Fonts/"
SERIF_BLACK = [FDIR+"rockb.ttf", FDIR+"BOOKOSB.TTF", FDIR+"georgiab.ttf", FDIR+"timesbd.ttf"]
SERIF_BOLD  = [FDIR+"georgiab.ttf", FDIR+"timesbd.ttf", FDIR+"BOOKOSB.TTF"]
SERIF       = [FDIR+"georgia.ttf", FDIR+"times.ttf"]


def find_font(cands, size):
    for p in cands:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                pass
    return ImageFont.load_default()


def main():
    ap = argparse.ArgumentParser(description="Compose engraving cut + period type into a finished ad.")
    ap.add_argument("--cut", required=True, help="engraving illustration PNG (the AI-generated cut)")
    ap.add_argument("--headline", required=True, help="big business name, e.g. GALLOWAY'S")
    ap.add_argument("--services", default="", help="e.g. GROCERIES  ·  GAS  ·  FEED")
    ap.add_argument("--town", default="", help="e.g. SHALLOTTE, N. C.")
    ap.add_argument("--kicker", default="", help="small top line, e.g. AROUND THE CLOCK")
    ap.add_argument("--tagline", default="", help="small bottom line of authentic copy")
    ap.add_argument("--out", required=True, help="output PNG path")
    ap.add_argument("--width", type=int, default=1500)
    ap.add_argument("--height", type=int, default=2150)
    ap.add_argument("--cut-width", type=int, default=820, help="px width to place the cut (keep near native to avoid blur)")
    a = ap.parse_args()

    W, H = a.width, a.height
    CREAM, INK = (245, 240, 228), (22, 19, 15)
    img = Image.new("RGB", (W, H), CREAM)
    d = ImageDraw.Draw(img)

    def fit(text, cands, max_w, start, mn=22):
        s = start
        while s > mn:
            f = find_font(cands, s)
            if d.textlength(text, font=f) <= max_w:
                return f
            s -= 4
        return find_font(cands, mn)

    def ctext(text, font, y, tracking=0, color=INK):
        if tracking:
            tot = sum(d.textlength(c, font=font) + tracking for c in text) - tracking
            x = (W - tot) / 2
            for c in text:
                d.text((x, y), c, font=font, fill=color)
                x += d.textlength(c, font=font) + tracking
        else:
            d.text(((W - d.textlength(text, font=font)) / 2, y), text, font=font, fill=color)

    def rule(y, thick=5, pad=100):
        d.line([pad, y, W - pad, y], fill=INK, width=thick)

    d.rectangle([30, 30, W-30, H-30], outline=INK, width=12)
    d.rectangle([52, 52, W-52, H-52], outline=INK, width=3)

    pad = 100
    cw = W - 2 * pad
    y = 120

    if a.kicker:
        kf = fit(a.kicker, SERIF_BOLD, cw*0.75, 62)
        ctext(a.kicker, kf, y, tracking=10); y += 96
        rule(y, 4); y += 44

    hf = fit(a.headline, SERIF_BLACK, cw, 320)
    hb = hf.getbbox(a.headline)
    ctext(a.headline, hf, y); y += (hb[3]-hb[1]) + 54

    if a.services:
        sf = fit(a.services, SERIF_BOLD, cw*0.92, 100)
        ctext(a.services, sf, y); y += 132
    rule(y, 3); y += 42

    cut = ImageOps.autocontrast(Image.open(a.cut).convert("L"), cutoff=1)
    tw = a.cut_width
    cut = cut.resize((tw, int(cut.height * tw / cut.width)))
    ink = Image.new("RGBA", cut.size, INK + (0,))
    ink.putalpha(cut.point(lambda p: 255 - p))   # dark ink opaque, white paper transparent
    img.paste(ink, ((W - tw)//2, y), ink); y += cut.height + 34
    rule(y, 3); y += 42

    if a.town:
        lf = fit(a.town, SERIF_BLACK, cw, 160)
        ctext(a.town, lf, y); y += lf.getbbox(a.town)[3] + 40

    if a.tagline:
        tf = fit(a.tagline, SERIF, cw*0.95, 62)
        ctext(a.tagline, tf, y); y += 90

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    img.save(a.out)
    print(f"Saved: {a.out} | final y {y} of {H}" + ("  (OVERFLOW — bump --height)" if y > H-52 else ""))


if __name__ == "__main__":
    main()
